spring.application.name=calendly

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/calendly_clone
spring.datasource.username=postgres
spring.datasource.password=Sasikala@2361
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
